version: '3.8'

services:
  laravel:
    build:
      context: ./backend-laravel
    container_name: laravel-api
    entrypoint: ["sh", "./entrypoint.sh"]
    volumes:
      - ./backend-laravel:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - ml
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=deliver_predictor
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - APP_KEY=base64:your_app_key_here # 請替換為 Laravel APP Key
      - SENTRY_DSN=${SENTRY_DSN_SECRET}
      # 若要使用 Reverb，可在此處新增環境變數
      # - REVERB_HOST=reverb
      # - REVERB_PORT=8080

  ml:
    build:
      context: ./ml-predictor-api
    container_name: predictor-api
    ports:
      - "8000:8000"
    environment:
      - SENTRY_DSN=${SENTRY_DSN_SECRET}

  vue:
    build:
      context: ./frontend-vue3
    container_name: vue-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://nginx/api
    
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
      - vue
      
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=deliver_predictor
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      
  # 參考：若要新增 Laravel Reverb 服務，可以取消註解以下設定
  # reverb:
  #   image: laravel/reverb:latest
  #   container_name: laravel-reverb
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - REVERB_APP_ID=YOUR_APP_ID
  #     - REVERB_APP_KEY=YOUR_APP_KEY
  #     - REVERB_APP_SECRET=YOUR_APP_SECRET
  #     - REVERB_HOST=0.0.0.0

volumes:
  mysql-data:
