name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install PHP dependencies
        run: composer install --no-ansi --no-interaction --no-progress
        working-directory: ./api-server

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit tests/Feature/PredictTest.php
        working-directory: ./api-server

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: pip install -r ml-api/requirements.txt
      - name: Run Pytest tests
        run: pytest ml-api/tests/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Node dependencies
        run: npm install
        working-directory: ./web-app
      - name: Run Vitest tests
        run: npm run test
        working-directory: ./web-app

  build_and_push_images:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push api-server image
        uses: docker/build-push-action@v5
        with:
          context: ./api-server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: yourdockerhub/deliverpredictor-laravel:${{ github.sha }}

      - name: Build and push ml-api image
        uses: docker/build-push-action@v5
        with:
          context: ./ml-api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: yourdockerhub/deliverpredictor-ml:${{ github.sha }}

      - name: Build and push web-app image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: yourdockerhub/deliverpredictor-vue:${{ github.sha }}
